import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, Layout } from "antd";
import theme from "@/theme/themeConfig";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { cookies } from "next/headers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => {
  const cookieStore = cookies();
  const token = cookieStore.get("token")?.value;
  return (
    <html lang="en">
      <body>
        <ConfigProvider theme={theme}>
          <Layout className="overflow-y-auto min-h-dvh relative">
            <AntdRegistry>
              <>
                <Header token={token} /> {/* Add the 'token' prop */}
                {children}
                <Footer />
              </>
            </AntdRegistry>
          </Layout>
        </ConfigProvider>
      </body>
    </html>
  );
};

export default RootLayout;
