version: '3.8'

services:
    userdb:
      container_name: userdb
      image: postgres
      ports:
      - "5436:5432"
      environment:
        POSTGRES_USER: abdulkadir
        POSTGRES_PASSWORD: 123456
        POSTGRES_DB: userdb
      volumes:
      - userdb:/var/lib/postgresql/data
      networks:
      - realestate
    advert:
        container_name: advert
        image: postgres
        ports:
        - "5437:5432"
        environment:
            POSTGRES_USER: abdulkadir
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: advert
        volumes:
        - advert:/var/lib/postgresql/data
        networks:
        - realestate
    orderdb:
        container_name: orderdb
        image: postgres
        ports:
        - "5438:5432"
        environment:
          POSTGRES_USER: abdulkadir
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: orderdb
        volumes:
        - orderdb:/var/lib/postgresql/data
        networks:
        - realestate
    paymentdb:
        container_name: paymentdb
        image: postgres
        ports:
        - "5439:5432"
        environment:
          POSTGRES_USER: abdulkadir
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: paymentdb
        volumes:
        - paymentdb:/var/lib/postgresql/data
        networks:
        - realestate
    rabbitmq-advert:
      container_name: rabbitmq-advert
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - realestate
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: 123456
    rabbitmq-order:
      container_name: rabbitmq-order
      image: rabbitmq:3-management
      ports:
        - "5673:5672"
        - "15673:15672"
      networks:
        - realestate
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: 123456
volumes:
  userdb:
  advert:
  orderdb:
  paymentdb:
  rabbitmq-advert:
  rabbitmq-order:

networks:
  realestate:
    driver: bridge
