spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/orderdb
    username: abdulkadir
    password: 123456
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: 123456



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  application:
    name: order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083  # Set the port to 8082 or any other available port
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

# Custom RabbitMQ settings
order:
  queue: orderStatusQueue
  exchange: order-exchange
  routingKey: order.status.#