spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - authorization
              - content-type
              - x-auth-token
            exposedHeaders:
              - x-auth-token
      routes:
        - id: user_route
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: payment_route
          uri: lb://payment
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1

        - id: advert_route
          uri: lb://advert
          predicates:
            - Path=/advert/**
          filters:
            - StripPrefix=1

        - id: order_route
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

        - id: auth_route
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

jwt:
  secret: rrxyPsPejUO9swnopDq3pxZigUA3eDA47fkYcuzB9I4=

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG