spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_route
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: package_route
          uri: lb://package
          predicates:
            - Path=/package/**
        - id: payment_route
          uri: lb://payment
          predicates:
            - Path=/payment/**
        - id: advert_route
          uri: lb://advert
          predicates:
            - Path=/advert/**
        - id: order_route
          uri: lb://order
          predicates:
            - Path=/order/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8080
