spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/userdb
    username: abdulkadir
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: auth

jwt:
  secret: rrxyPsPejUO9swnopDq3pxZigUA3eDA47fkYcuzB9I4=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085  # Set the port to 8081 or any other available port