spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/advert
    username: abdulkadir
    password: 123456
    driver-class-name: org.postgresql.Driver


  security:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  application:
    name: advert

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082  # Set the port to 8082 or any other available port
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

