spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/advert
    username: abdulkadir
    password: 123456
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

  application:
    name: advert
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082  # Set the port to 8082 or any other available port
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
# Custom RabbitMQ settings
status:
  queue: advertStatusQueue
  exchange: advert-exchange
  routingKey: advert.status.#

aws:
  accessKeyId: AKIAW3MEB4Y6KVHH5V3J
  secretKey: 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
  region: us-east-1
  bucketName: realestate-image-bucket



